title:            Julius Šėporaitis
tagline:          Pamastymai ir Pabambėjimai
description:      Describe your website.
#Comment out url when working locally to resolve base urls correctly
url: http://www.seporaitis.lt


# Owner/author information
owner:
  name:           Julius Šėporaitis
  avatar:         avatar.png
  bio:            "Smalsus Žmogus"
  email:          julius@seporaitis.net
  twitter:        seporaitis
  github:         seporaitis
  disqus:         seporaitis-lt
  # Plug in your disqus shortname!


# Links to include in top navigation
# For external links add external: true
links:
  - title: Apie
    url: /apie

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:day/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
